version: '3'
services:
  discovery:
    image: consul:1.9
    ports:
      - 8500:8500

  service-community:
    build:
      context: community
    image: bourseplay/service-community
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery -DCONSUL_PORT=8500
    depends_on:
      - discovery
      - service-auth

  service-auth:
    build:
      context: authentification
    image: bourseplay/service-auth
    restart: always
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery -DCONSUL_PORT=8500
    depends_on:
      - discovery

  gateway:
    build:
      context: gateway
    image: bourseplay/gateway
    ports:
      - 8080:8080
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
    depends_on:
      - discovery