version: '3'
services:
  discovery:
    image: consul:1.9
    ports:
      - "8500:8500"
    networks:
      - my_network
  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: service
      RABBITMQ_DEFAULT_PASS: service
    networks:
      - my_network

  mysql_database_auth:
    image: mysql:latest
    container_name: db_auth
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_user_password
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      GOSU_VERSION: 1.16
      MYSQL_MAJOR: innovation
      MYSQL_VERSION: 8.3.0-1.el8
      MYSQL_SHELL_VERSION: 8.3.0-1.el8
    volumes:
      - /var/lib/mysql
    ports:
      - "3306:3306"
    restart: "no"
    networks:
      - my_network

  mysql_database_bourse:
    image: mysql:latest
    container_name: db_bourse
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_user_password
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      GOSU_VERSION: 1.16
      MYSQL_MAJOR: innovation
      MYSQL_VERSION: 8.3.0-1.el8
      MYSQL_SHELL_VERSION: 8.3.0-1.el8
    volumes:
      - /var/lib/mysql
      - ./ticker.sql:/docker-entrypoint-initdb.d/ticker.sql
    ports:
      - "3307:3306"
    restart: "no"
    networks:
      - my_network

  mysql_database_community:
    image: mysql:latest
    container_name: db_community
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_user_password
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      GOSU_VERSION: 1.16
      MYSQL_MAJOR: innovation
      MYSQL_VERSION: 8.3.0-1.el8
      MYSQL_SHELL_VERSION: 8.3.0-1.el8
    volumes:
      - /var/lib/mysql
    ports:
      - "3308:3306"
    restart: "no"
    networks:
      - my_network

  mysql_database_portefeuille:
    image: mysql:latest
    container_name: db_portefeuille
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_user_password
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      GOSU_VERSION: 1.16
      MYSQL_MAJOR: innovation
      MYSQL_VERSION: 8.3.0-1.el8
      MYSQL_SHELL_VERSION: 8.3.0-1.el8
    volumes:
      - /var/lib/mysql
    ports:
      - "3309:3306"
    restart: "no"
    networks:
      - my_network

  mysql_database_automation:
    image: mysql:latest
    container_name: db_automation
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: your_database
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_user_password
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      GOSU_VERSION: 1.16
      MYSQL_MAJOR: innovation
      MYSQL_VERSION: 8.3.0-1.el8
      MYSQL_SHELL_VERSION: 8.3.0-1.el8
    volumes:
      - /var/lib/mysql
    ports:
      - "3310:3306"
    restart: "no"
    networks:
      - my_network

  service-community:
    build:
      context: ./community
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - my_network
    ports:
      - "8082:8082"
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery -DCONSUL_PORT=8500
    depends_on:
      - discovery
      - service-auth
      - mysql_database_community

  service-auth:
    build:
      context: ./authentification
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - my_network
    ports:
      - "8081:8081"
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery -DCONSUL_PORT=8500
    depends_on:
      - discovery
      - mysql_database_auth

  service-bourse:
    build:
      context: ./bourse
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - my_network
    ports:
      - "8083:8083"
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery -DCONSUL_PORT=8500
    depends_on:
      - discovery
      - service-auth
      - mysql_database_bourse
      - rabbitmq

  service-portefeuille:
    build:
      context: ./portefeuille
      dockerfile: ./Dockerfile
    restart: always
    networks:
      - my_network
    ports:
      - "8085:8085"
    environment:
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery -DCONSUL_PORT=8500
    depends_on:
      - discovery
      - service-auth
      - mysql_database_portefeuille
      - rabbitmq
  gateway:
    build:
      context: ./gateway
      dockerfile: ./Dockerfile
    networks:
      - my_network
    ports:
      - "8080:8080"
    environment:
      - DEBUG=true
      - JAVA_TOOL_OPTIONS=
        -DCONSUL_HOST=discovery
    depends_on:
      - discovery
      - service-auth
      - service-bourse
      - service-community
      - service-portefeuille

  service-front:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    networks:
      - my_network
    ports:
      - "3000:3000"
    depends_on:
      - gateway
networks:
  my_network: