spring:
  application:
    name: service-community
  cloud:
    consul:
      discovery:
        register: true
      host: ${CONSUL_HOST:lol}
      port: ${CONSUL_PORT:8500}
      ribbon:
        enabled: false
  datasource:
    url: jdbc:mysql://mysql_database_community:3306/your_database
    username: ${MYSQL_USER:your_user}
    password: ${MYSQL_PASSWORD:your_user_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
jwt:
  public.key: ${JWT_PUBLIC_KEY:classpath:app.pub}
server:
  port: 8082

