server:
  port: 8080
security:
  basic:
    enabled: false
  ignored: /**
spring:
  application:
    name: gateway
  cloud:
    consul:
      discovery:
        register: true
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: auth
          uri: lb://service-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - RewritePath=/api/auth(?<segment>/?.*), /auth$\{segment}
            - PreserveHostHeader=true
        - id: community
          uri: lb://service-community
          predicates:
            - Path=/api/community/**
          filters:
            - RewritePath=/api/community(?<segment>/?.*), /community/v1$\{segment}
            - PreserveHostHeader
        - id: bourse
          uri: lb://service-bourse
          predicates:
            - Path=/api/bourse/**
          filters:
            - RewritePath=/api/bourse(?<segment>/?.*), /bourse$\{segment}
            - PreserveHostHeader=true