spring:
  application:
    name: service-portefeuille
  cloud:
    consul:
      discovery:
        hostname: ${CONSUL_HOST:localhost}
        port: ${CONSUL_PORT:8500}
  datasource:
    url: jdbc:mysql://localhost:3306/your_database # TODO Changer pour la bonne base
    username: your_user
    password: your_user_password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
jwt:
  public.key: classpath:app.pub
server:
  port: 8080