server:
  port: 8081
security:
  basic:
    enabled: false
  ignored: /**
spring:
  application:
    name: service-auth
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
    consul:
      discovery:
        register: true
      host: ${CONSUL_HOST:lol}
      port: ${CONSUL_PORT:8500}
      ribbon:
        enabled: false

  datasource:
    url: jdbc:mysql://mysql_database_auth:3306/your_database
    username: ${MYSQL_USER:your_user}
    password: ${MYSQL_PASSWORD:your_user_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


jwt:
  private.key: ${JWT_PRIVATE_KEY:classpath:app.key}
  public.key: ${JWT_PUBLIC_KEY:classpath:app.pub}

